version: 2

project_name: langz

before:
  hooks:
    - go mod tidy

builds:
  - id: langz
    binary: langz
    main: ./cmd/langz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: langz
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: tasnimzotder
    name: langz
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
